repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.35.0
    hooks:
      - id: terraform_validate
        args:
          - '--envs=AWS_DEFAULT_REGION="eu-west-1"'
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - "--args=--with-aggregate-type-defaults --no-escape --no-providers --no-requirements --sort-by-required"
      - id: terraform_tflint
        args:
          - 'args=--module'
      - id: terraform_tfsec
